ifndef::imagesdir[:imagesdir: ../images]

[[section-runtime-view]]
== Runtime View


ifdef::arc42help[]
[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...


.Further Information

See https://docs.arc42.org/section-6/[Runtime View] in the arc42 documentation.

****
endif::arc42help[]

=== Runtime Scenario 1 - Playing a game

The following diagram depicts the interaction between the user and the most notable modules of the application.

image::06_runtime_view-EN.svg[align="center"]

The interaction can be divided into these steps:

* **Logging in:** The user logs into the application. If they don't have  an account created, it will be necessary to sign up.
* **Starting the game: ** Once logged in, the user will start a new game.
* **Answering the questions: ** For each question, the four ellegible answers will be generated. Once per question, its info (question, image and possible answers) will be presented to the user via the GUI, and it will wait for their input. After the user inputs their answer, the score will be increased (or not) accordingly to the choosen answer.
* **Ending the game:** Once all the questions have been answered, the GUI will display the final score of the game.

Additional considerations:

* Once the game is finished, the user will be asked whether they'd like to start a new game. This diagram only portrays one game.
* In spite of simplicity, this diagram assumes the user already has an account.