ifndef::imagesdir[:imagesdir: ../images]

[[section-runtime-view]]
== Runtime View

=== Runtime Scenario 1 - Playing a game

The following diagram depicts the interaction between the user and the most notable modules of the application.

image::06_runtime_view-EN.svg[align="center"]

The interaction can be divided into these steps:

* **Logging in:** The user logs into the application. If they don't have  an account created, it will be necessary to sign up.
* **Starting the game: ** Once logged in, the user will start a new game.
* **Answering the questions: ** For each question, the four ellegible answers will be generated. Once per question, its info (question, image and possible answers) will be presented to the user via the GUI, and it will wait for their input. After the user inputs their answer, the score will be increased (or not) accordingly to the choosen answer.
* **Ending the game:** Once all the questions have been answered, the GUI will display the final score of the game.

Additional considerations:

* Once the game is finished, the user will be asked whether they'd like to start a new game. This diagram only portrays one game.
* In spite of simplicity, this diagram assumes the user already has an account.