ifndef::imagesdir[:imagesdir: ../images]

[[section-deployment-view]]


== Deployment View

=== Infrastructure Level 1

ifdef::arc42help[]
[role="arc42help"]
****
Describe (usually in a combination of diagrams, tables, and text):

* distribution of a system to multiple locations, environments, computers, processors, .., as well as physical connections between them
* important justifications or motivations for this deployment structure
* quality and/or performance features of this infrastructure
* mapping of software artifacts to elements of this infrastructure

For multiple environments or alternative deployments please copy and adapt this section of arc42 for all relevant environments.
****
endif::arc42help[]

image::07_deployment_view-EN.svg[align="center"]

Motivation::

The diagram portrays an overview of the distrubution of each element in the infraestructure, offering details about relationships between devices and communications. Understanding this diagram will help with identifying potential points of failure in the future.

Quality and/or Performance Features::

This design has been made taking in consideration potential performance and availability issues. Accessing data from the Wikidata servers, as well as the LLM, will ensure that their failure won't be fatal to the entire app. On the other hand, scheduling a secondary task to generate questions and answers will ensure that said questions are fully loaded before starting a game. This will also help with the performance of the app, as it will not be necessary to wait for the generation of questions during the game.

Mapping of Building Blocks to Infrastructure::

[options="header",cols="1,2"]
|===
| Device/Node        | Deployed Artifacts
| WIChat server      | Game app (Frontend: React, Backend: node.js), Question generation service
| Wikidata server    | Wikidata API to fetch data via SPARQL queries to dynamically generate questions
| OpenLLM server     | Open LLM (AI) designed to give hints during the game
|===