name: Check GHCR Permissions
on: workflow_dispatch

jobs:
  check-ghcr-permissions:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Check Package Permissions
      run: |
        echo "Checking permissions..."
        curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/orgs/arquisoft/packages?package_type=container
